# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-29 21:57
from __future__ import unicode_literals

from django.db import migrations, models
import helpers.director.model_func.cus_fields.cus_picture


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZhanXunModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='标题')),
                ('cover', helpers.director.model_func.cus_fields.cus_picture.PictureField(blank=True, max_length=400, verbose_name='封面')),
                ('content', models.TextField(blank=True, verbose_name='内容')),
                ('status', models.IntegerField(choices=[(0, '离线'), (1, '在线')], default=0, verbose_name='状态')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
    ]
