# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-30 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expolink', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zhanxunmodel',
            name='abstract',
            field=models.TextField(blank=True, verbose_name='摘要'),
        ),
    ]
